spring.application.name=airBnbApp

# DB Config (example)
spring.datasource.url=jdbc:postgresql://localhost:5432/your_db
spring.datasource.username=your_username
spring.datasource.password=your_password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.servlet.context-path=/api/v1

# JWT
jwt.secretKey=your_secret_key_here

# Stripe
stripe.secretKey=your_stripe_secret_key
stripe.webhookSecret=your_stripe_webhook_secret

# Frontend URL (for Stripe redirect)
frontend.url=http://localhost:3000

# Mail Config
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=your_email@gmail.com
spring.mail.password=your_app_password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true